repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: [--maxkb=5000]
      - id: check-merge-conflict
      - id: check-toml

  - repo: local
    hooks:
      - id: zola-build
        name: Zola build check
        language: system
        entry: zola check
        pass_filenames: false
        files: ^(content|templates|sass|config\.toml)/
