#!/usr/bin/env tsx
/**
 * Generate glossary page from all glossary shortcodes across content.
 * Walks content/deep-dives/, extracts glossary(term, def) calls,
 * deduplicates by term name (case-insensitive, keeps longest def),
 * and writes content/glossary.md.
 *
 * Usage: npx tsx scripts/generate-glossary.ts
 */

import { readFileSync, readdirSync, statSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';

function findMarkdownFiles(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      files.push(...findMarkdownFiles(full));
    } else if (entry.endsWith('.md') && entry !== '_index.md') {
      files.push(full);
    }
  }
  return files;
}

interface GlossaryEntry {
  term: string;
  def: string;
}

function extractGlossaryTerms(content: string): GlossaryEntry[] {
  const entries: GlossaryEntry[] = [];
  // Match both {{ glossary(...) }} and {% glossary(...) %} formats
  const re = /\{\{?\s*glossary\(\s*term\s*=\s*"([^"]+)"\s*,\s*def\s*=\s*"((?:[^"\\]|\\.)*)"\s*\)\s*\}?\}/g;
  let match;
  while ((match = re.exec(content)) !== null) {
    entries.push({
      term: match[1],
      def: match[2].replace(/\\"/g, '"'),
    });
  }
  return entries;
}

function main() {
  const contentDir = resolve(__dirname, '..', 'content', 'deep-dives');
  const files = findMarkdownFiles(contentDir);

  console.log(`Scanning ${files.length} content files...`);

  // Collect all terms, dedup by lowercase key (keep longest def)
  const termMap = new Map<string, GlossaryEntry>();

  for (const file of files) {
    const content = readFileSync(file, 'utf-8');
    const terms = extractGlossaryTerms(content);
    for (const entry of terms) {
      const key = entry.term.toLowerCase();
      const existing = termMap.get(key);
      if (!existing || entry.def.length > existing.def.length) {
        termMap.set(key, { term: entry.term, def: entry.def });
      }
    }
  }

  // Sort alphabetically by term name (case-insensitive)
  const sorted = [...termMap.values()].sort((a, b) => a.term.toLowerCase().localeCompare(b.term.toLowerCase()));

  console.log(`Found ${sorted.length} unique glossary terms`);

  // Build glossary page
  const lines = [
    '+++',
    'title = "Glossary"',
    'template = "glossary.html"',
    'description = "Technical terms defined without the bullshit."',
    'date = 2026-03-09',
    '+++',
    '',
    '<!-- Auto-generated by scripts/generate-glossary.ts — do not edit manually -->',
    '',
    '<dl>',
  ];

  for (const entry of sorted) {
    lines.push('');
    lines.push(`<dt>${entry.term}</dt>`);
    lines.push(`<dd>${entry.def}</dd>`);
  }

  lines.push('');
  lines.push('</dl>');
  lines.push('');

  const glossaryPath = resolve(__dirname, '..', 'content', 'glossary.md');
  writeFileSync(glossaryPath, lines.join('\n'));
  console.log(`Wrote glossary to ${glossaryPath}`);
}

main();
